name: VCMI-DEF-Converter

on:
  push:
    branches: main
  pull_request:
  workflow_dispatch:

jobs:
  build-win-x64:
    name: Build for Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12 (x64)
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Compile with Nuitka (x64)
        shell: cmd
        run: |
          nuitka def2json.py ^
            --standalone ^
            --onefile ^
            --enable-plugin=tk-inter ^
            --output-dir=build ^
            --nofollow-imports ^
            --windows-disable-console ^
            --assume-yes-for-downloads

      - name: Rename EXE
        run: |
          Rename-Item -Path build\def2json.exe -NewName def2json-win-x64.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: def2json-win-x64
          path: build/def2json-win-x64.exe

  build-win-x86:
    name: Build for Windows x86
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12 (x86)
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          architecture: 'x86'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Compile with Nuitka (x86)
        shell: cmd
        run: |
          nuitka def2json.py ^
            --standalone ^
            --onefile ^
            --enable-plugin=tk-inter ^
            --output-dir=build ^
            --nofollow-imports ^
            --windows-disable-console ^
            --assume-yes-for-downloads

      - name: Rename EXE
        run: |
          Rename-Item -Path build\def2json.exe -NewName def2json-win-x86.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: def2json-win-x86
          path: build/def2json-win-x86.exe

  build-linux-x64:
    name: Build for Linux x64
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install nuitka

      - name: Compile with Nuitka
        run: |
          nuitka def2json.py \
            --standalone \
            --onefile \
            --enable-plugin=tk-inter \
            --output-dir=build \
            --nofollow-imports \
            --assume-yes-for-downloads

      - name: Rename ELF
        run: mv build/def2json.bin def2json-linux-x64

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: def2json-linux-x64
          path: def2json-linux-x64
